#msg_parser:
#    resource: "@ParserBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

parser:
    resource: '@ParserBundle/Controller/'
    type: annotation

logout:
    path: /logout

user_registration:
    path:     /signup
    defaults: { _controller: AppBundle:Registration:signup }

app_comment:
    resource: 'routing/api.yml'
    prefix: /api

app_parser:
    resource: |
        alias: app.parser
    type: sylius.resource_api
    prefix: /api
