# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$8G5GhE37fwPbPBwBW4mw4.KXNhzkCtqgBHbIea..hC7xas64iH73C
                        roles: 'ROLE_USER'
                    test:
                        password: $2y$12$8G5GhE37fwPbPBwBW4mw4.KXNhzkCtqgBHbIea..hC7xas64iH73C
                        roles: 'ROLE_ADMIN'
                    admin:
                        password: $2y$12$WkrnLMDlBz9PBBk8DWgzHuOjGr/I5n4fnvpANkFucK1PY5NSw/oua
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }