<?php

namespace MsgParserBundle\Repository;

/**
 * MsgParserClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgParserClassesRepository extends \Doctrine\ORM\EntityRepository
{
}
