<?php

namespace MsgParserBundle\Repository;

/**
 * MsgParserInterfacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgParserInterfacesRepository extends \Doctrine\ORM\EntityRepository
{
}
