<?php

namespace MsgParserBundle\Repository;

/**
 * MsgParserNamespaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgParserNamespaceRepository extends \Doctrine\ORM\EntityRepository
{
}
