sylius_grid:
    grids:
        app_api_comment:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Comment
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig # This will be a checkbox field
